Split image versions from URLs to make overriding easier
vexxhost/ansible-collection-kubernetes pull request #142
Opened 2024-11-05 13:06 UTC by andrewbonney

This PR splits the version out into a separate variable from image URLs. In doing so, when it is necessary to override image URLs to reference an offline registry, we can reference the image version(s) which match the version of this collection which we are pinning to.

2024-11-15 15:10 UTC, mnaser requested changes

2024-11-15 15:10 UTC, mnaser commented on roles/cert_manager/defaults/main.yml
> +cert_manager_image_version: "v1.11.5"
Do you mind if we use `tag` instead?

2024-11-15 15:10 UTC, mnaser commented on roles/cilium/defaults/main.yml
> +cilium_node_image_version: "v1.14.8@sha256:7fca3ba4b04af066e8b086b5c1a52e30f52db01ffc642e7db0a439514aed3ada"
Same here, we can also honestly drop the SHA256 stuff too.

2024-11-15 15:10 UTC, mnaser commented on roles/haproxy/defaults/main.yml
> +haproxy_image_version: "2.5"
Same here

2024-11-15 15:10 UTC, mnaser commented on roles/keepalived/defaults/main.yml
> +keepalived_image_version: "2.0.19"
and here

2024-11-15 15:10 UTC, mnaser commented on roles/kube_vip/defaults/main.yml
> +kube_vip_image_version: "v0.6.4"
and finally here

2024-11-15 15:14 UTC, andrewbonney commented on roles/cert_manager/defaults/main.yml
> +cert_manager_image_version: "v1.11.5"
Sure. I was just aiming for consistency with ansible-collection-containers which seems to use `_version` across the board.

2024-12-10 15:30 UTC, andrewbonney commented
@mnaser would you mind having another look at this and the containers patch?

2025-08-31 20:45 UTC, mnaser commented
@andrewbonney @jrosser can you allow maintainers to edit this PR, alternatively could you rebase/merge main into this?  I'd like to push to get this in but I cannot edit the PR.

2025-09-01 09:38 UTC, andrewbonney commented
Done - unfortunately I can't give permission on it, but it's rebased.

2025-09-01 14:59 UTC, merged